/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthType: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Movie: { // root type
    creatorId: string; // String!
    description: string; // String!
    directorName: string; // String!
    id: number; // Int!
    movieName: string; // String!
    releaseDate: string; // String!
  }
  Mutation: {};
  Query: {};
  Review: { // root type
    comment?: string | null; // String
    id: number; // Int!
    movieId: number; // Int!
    rating?: number | null; // Float
    userId: number; // Int!
  }
  User: { // root type
    email: string; // String!
    id: number; // Int!
    password: string; // String!
    username: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthType: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Movie: { // field return type
    createdBy: NexusGenRootTypes['User'] | null; // User
    creatorId: string; // String!
    description: string; // String!
    directorName: string; // String!
    id: number; // Int!
    movieName: string; // String!
    releaseDate: string; // String!
  }
  Mutation: { // field return type
    createMovie: NexusGenRootTypes['Movie']; // Movie!
    createReview: NexusGenRootTypes['Review']; // Review!
    deleteMovie: NexusGenRootTypes['Movie']; // Movie!
    deleteReview: NexusGenRootTypes['Review']; // Review!
    login: NexusGenRootTypes['AuthType']; // AuthType!
    register: NexusGenRootTypes['AuthType']; // AuthType!
    updateMovie: NexusGenRootTypes['Movie']; // Movie!
    updateReview: NexusGenRootTypes['Review']; // Review!
  }
  Query: { // field return type
    movie: NexusGenRootTypes['Movie'][]; // [Movie!]!
    movies: NexusGenRootTypes['Movie'][]; // [Movie!]!
    reviewById: NexusGenRootTypes['Review'] | null; // Review
    reviews: NexusGenRootTypes['Review'][]; // [Review!]!
    reviewsByMovie: NexusGenRootTypes['Review'][]; // [Review!]!
    reviewsByMoviePaginated: NexusGenRootTypes['Review'][]; // [Review!]!
    searchMovies: NexusGenRootTypes['Movie'][]; // [Movie!]!
  }
  Review: { // field return type
    comment: string | null; // String
    id: number; // Int!
    movie: NexusGenRootTypes['Movie'] | null; // Movie
    movieId: number; // Int!
    rating: number | null; // Float
    user: NexusGenRootTypes['User'] | null; // User
    userId: number; // Int!
  }
  User: { // field return type
    email: string; // String!
    id: number; // Int!
    password: string; // String!
    username: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AuthType: { // field return type name
    token: 'String'
    user: 'User'
  }
  Movie: { // field return type name
    createdBy: 'User'
    creatorId: 'String'
    description: 'String'
    directorName: 'String'
    id: 'Int'
    movieName: 'String'
    releaseDate: 'String'
  }
  Mutation: { // field return type name
    createMovie: 'Movie'
    createReview: 'Review'
    deleteMovie: 'Movie'
    deleteReview: 'Review'
    login: 'AuthType'
    register: 'AuthType'
    updateMovie: 'Movie'
    updateReview: 'Review'
  }
  Query: { // field return type name
    movie: 'Movie'
    movies: 'Movie'
    reviewById: 'Review'
    reviews: 'Review'
    reviewsByMovie: 'Review'
    reviewsByMoviePaginated: 'Review'
    searchMovies: 'Movie'
  }
  Review: { // field return type name
    comment: 'String'
    id: 'Int'
    movie: 'Movie'
    movieId: 'Int'
    rating: 'Float'
    user: 'User'
    userId: 'Int'
  }
  User: { // field return type name
    email: 'String'
    id: 'Int'
    password: 'String'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createMovie: { // args
      description: string; // String!
      directorName: string; // String!
      movieName: string; // String!
      releaseDate: string; // String!
    }
    createReview: { // args
      comment: string; // String!
      movieId: number; // Int!
      rating: number; // Float!
    }
    deleteMovie: { // args
      id: number; // Int!
    }
    deleteReview: { // args
      id: number; // Int!
    }
    login: { // args
      password: string; // String!
      username: string; // String!
    }
    register: { // args
      email: string; // String!
      password: string; // String!
      username: string; // String!
    }
    updateMovie: { // args
      description: string; // String!
      directorName: string; // String!
      id: number; // Int!
      movieName: string; // String!
      releaseDate: string; // String!
    }
    updateReview: { // args
      comment: string; // String!
      id: number; // Int!
      movieId: number; // Int!
      rating: number; // Float!
    }
  }
  Query: {
    movie: { // args
      id: number; // Int!
    }
    reviewById: { // args
      id: number; // Int!
    }
    reviews: { // args
      filter?: string | null; // String
      limit?: number | null; // Int
      page?: number | null; // Int
      sort?: string | null; // String
    }
    reviewsByMovie: { // args
      movieId: number; // Int!
    }
    reviewsByMoviePaginated: { // args
      limit: number; // Int!
      movieId: number; // Int!
      page: number; // Int!
    }
    searchMovies: { // args
      limit?: number | null; // Int
      offset?: number | null; // Int
      query: string; // String!
      sort?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}